<a href="https://colab.research.google.com/github/TejaswiReddySandi/ml-academic-assignments/blob/main/KNN_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import scikit-learn dataset library
from sklearn import datasets

In [ ]:
#load dataset
irisDataset = datasets.load_iris()
print(irisDataset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
#check records of the target set
print(irisDataset.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
type(irisDataset.target)

numpy.ndarray

In [ ]:
#check top 5 records of the feature set
print(irisDataset.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
type(irisDataset)

sklearn.utils.Bunch

In [ ]:
print(irisDataset.target[0:5])

[0 0 0 0 0]


In [ ]:
#check the shape of the dataset using shape
print(irisDataset.data.shape)

(150, 4)


In [ ]:
#import train_test_split function
from sklearn.model_selection import train_test_split

In [ ]:
#split dataset into training set and test set 
X_train, X_test, y_train, y_test = train_test_split(irisDataset.data, irisDataset.target, test_size=0.2)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
#create KNN Classifier
knn2 = KNeighborsClassifier(n_neighbors=2)

In [ ]:
#train the model using the training sets
knn2.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [ ]:
#predict the response for test dataset
y_pred2 = knn2.predict(X_test)

In [ ]:
from sklearn import metrics

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred2))

Accuracy: 0.9666666666666667


In [ ]:
#import knearest neighbors classifier model
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
#create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
#train the model using the training sets
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
#predict the response for the dataset
y_pred = knn.predict(X_test)

In [ ]:
#import scikit-learn metrics module for accuracy calculation
from sklearn import metrics 

In [ ]:
#model accuracy how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
#create KNN Classifier
knn1 = KNeighborsClassifier(n_neighbors=7)

In [ ]:
#train the model using the training sets
knn1.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
#predict the response for test dataset
y_pred1 = knn1.predict(X_test)

In [ ]:
#import scikit-learn metrics module for accuracy calculation
from sklearn import metrics 

In [ ]:
#model accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred1))

Accuracy: 1.0
